### ISSUE TITLE
franklin

### ISSUE THREAD

**Issue by D042888-2** [SOSP-OS/android_manifest#1]
Hello!
You shouldn't have deleted franklin.
The problem is the wrong twrp device, I've redone it, I'll post the sources later.
The problem in franklin is primarily in the partitioning, I have a 16 GB device.
Secondly, the problem is in the kernel

**Comment by D042888-2** [comment]
Hello! You shouldn't have deleted franklin. The problem is the wrong twrp device, I've redone it, I'll post the sources later. The problem in franklin is primarily in the partitioning, I have a 16 GB device. Secondly, the problem is in the kernel

**Comment by Gnathvm** [comment]
franklin tree was just for testing purpose.The android 13 doesn't support the stock franklin kernel.I have a separate tree for twrp. If you want a working twrp with latest twrp source.PM me

**Comment by D042888-2** [comment]
I wrote to the email
